input_dim: 8
hidden_dim: 128
lr: 0.001
gamma: 0.99
episodes: 2000
explore_rate: 0.05
curriculum_static_episodes: 800
curriculum_easy_irl_episodes: 1600
save_name: "best_model.pt"
onnx_name: "model.onnx"
